[package]

name = "avcodec55"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avutil52]

git = "https://github.com/mewlips/rust-ffmpeg.git"
path = "avutil52"

[[lib]]

name = "avcodec55"
