[package]

name = "avdevice55"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avformat55]

git = "https://github.com/mewlips/rust-ffmpeg.git"
path = "avformat55"

[[lib]]

name = "avdevice55"
