[package]

name = "avfilter3"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avutil52]

git = "file:///home/mewlips/myrepo/rust-ffmpeg"
path = "avutil52"

[dependencies.avcodec54]

git = "file:///home/mewlips/myrepo/rust-ffmpeg"
path = "avcodec54"

[[lib]]

name = "avfilter3"
