[package]

name = "avfilter3"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avutil52]

path = "../avutil52"

[dependencies.avcodec54]

path = "../avcodec54"

[lib]

name = "avfilter3"

[dependencies]
libc = "*"

