[package]

name = "avformat55"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avutil52]

path = "../avutil52"

[dependencies.avcodec55]

path = "../avcodec55"

[[lib]]

name = "avformat55"
