[package]

name = "swresample0"
version = "0.1.0"
authors = [ "mewlips@gmail.com" ]

[dependencies.avutil52]

git = "file:///home/mewlips/myrepo/rust-ffmpeg"
path = "avutil52"

[[lib]]

name = "swresample0"
